apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zidxb92p8-java-springboot
  janus-idp.io/tekton: zidxb92p8-java-springboot
  backstage.io/kubernetes-id: zidxb92p8-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zidxb92p8-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
